### ISSUE TITLE
Remote port forwarding

### ISSUE THREAD

**Issue by edumarket** [mhzed/wstunnel#1]
Hi!
Kindly direct how to implement server to client port forwarding.
For example:
Remote client with ip x.x.x.x connect to server y.y.y.y:zzzz and this ports forwards to websoket client with u.u.u.u:ssss?

**Comment by mhzed** [comment]
Currently not supported.  However you can do this:
1. setup a ssh tunnel from client to server via wstunnel, i.e. client:2222 wstunnel to server:22
2. then you can do reverse tunnel via SSH.

**Comment by edumarket** [comment]
Thank you.
I do it in this way now, but i’d like to do in via websocket.

Thank you.
