### ISSUE TITLE
SSL over proxy

### ISSUE THREAD

**Issue by dvengrov** [mhzed/wstunnel#11]
I tried use the SSL option with proxy , is it supported ?

**Comment by erebe** [comment]
If you are on linux use proxychains to manage the proxy.
I ran into trouble when combining ssl and proxy with wstunnel, but wstunnel with ssl and proxychains to manage and everything went fine.

**Comment by mhzed** [comment]
Yes always establish a SSH tunnel over wstunnel first.  This is how I always use it, secure and stable.
