### ISSUE TITLE
Note about ws:// ports

### ISSUE THREAD

**Issue by lapsio** [mhzed/wstunnel#16]
I'd just like to note that as ws is based on http it can be used on port 80. Furthermore it's using upgrade request so it's actually possible to create hybrid http+ws server listening on single port, at least using node. Also it implies that ws is routable via nginx so realistically user can use path routing or subdomain routing in nginx for example to set up wstunnel "next to" actual http server without any significant trouble.

All of it creates quite interesting use case for wstunnel apart from punching through firewalls: one can use it for tunneling single service for multiple machines exposed under single public IP for example:

    ssh.machine1.hostname.com
    ssh.machine2.hostname.com

or if subdomains are not available option then even using path:

    hostname.com/machine1/ssh
    hostname.com/machine2/ssh

Surprisingly it seems to be **the only** option I found to actually perform ssh hostname/path based routing using single port and single public IP for multiple machines running the same service - as long as we don't want to create dedicated ssh gateway with accounts for absolutely all users or full blown VPN (which is obviously inconvenient as creating such gateway brings further accounts management overhead and security implications). Paired with stunnel TLS tunneling for high security encryption and certificate based authentication it's interesting options for VNC and other management protocols as well.

**Comment by mhzed** [comment]
Good point: when the server is launched without '-t' option, it exposes a single http[s] endpoint that allows the client to tunnel anywhere (that the server can connect to).  But then you better make sure the http[s] endpoint is protected by SSL and password, otherwise, this leaves a giant security hole in your system.
