### ISSUE TITLE
Node engine version restrictions in package.json

### ISSUE THREAD

**Issue by thomasnordquist** [mhzed/wstunnel#19]
Is there a reason for the specific node version requirements ?
The `yarn` package manager won't let me install this package.
https://github.com/mhzed/wstunnel/blob/master/package.json#L23
## yarn output
```
error wstunnel@1.2.1: The engine "node" is incompatible with this module. Expected version "~0.10.21".
```

I'm currently running node version **v7.10.0** which makes the package "incompatible".

**Comment by mhzed** [comment]
No there isn't a reason.  Though I haven't tested it, I am pretty certain it should work.
