### ISSUE TITLE
Support for shadowsocks?

### ISSUE THREAD

**Issue by cbwang2016** [mhzed/wstunnel#20]
Is it possible and convenient to make this project work as a SIP003 plugin for shadowsocks? If so, it would be amazing to use shadowsocks through websocket, or even through Cloudflare free CDN.

**Comment by mhzed** [comment]
Yes it's definitely possible and most likely convenient.  Feel free to give it a try and send me a pull request, :)
Btw for SOCKS5 proxy I usually go with "ssh -D" over wstunnel.

**Comment by cbwang2016** [comment]
@mhzed this seems possible, but I have a little question: how to determine whether the shadowsocks is ss-local or ss-server?
