### ISSUE TITLE
websocket native extensions doesn't build

### ISSUE THREAD

**Issue by hnz101** [mhzed/wstunnel#24]
With the current dependency setting for websocket "^1.0.24" nodejs pulls an very old version of websocket (1.0.8) which doesn't build correct.
I tested a change to ">=1.0.24" which than pulls 1.0.25 and builds without any problems.
Could you please change the dependency?
I didn't  checked the other ^... dependencies, but perhaps there are also used unnecessary old versions.

**Comment by mhzed** [comment]
I've bumped version to 1.0.25.

Btw you probably had 1.0.8 cached locally and thus npm used it instead of 1.0.24 (since semantically they are compatible).   A fresh npm install should fetch the later version.
