### ISSUE TITLE
proxy setting seems not to work

### ISSUE THREAD

**Issue by kleinth328** [mhzed/wstunnel#26]
When running wstunnel as client and using the -p switch to enable proxy usage the program fails because it tries to resolve the hostname of the remote machine. But that's why i'm using the proxy. The remote server can neither be resolved in DNS nor can a TCP connection beeing opend for it.

I'm in a corporate network behind an HTTP proxy using authentication. No Internet DNS, no default route to the internet.

Commandlines used:
U:\node_modules>node wstunnel/bin/wstt.js -c -t stdio:<wstunnel server hostname>:8080 -p http://proxy.local:8080 https://<wstunnel server IP>:8080
[Mar 07 2018 14:40:48.532 GMT+0100](wstunnel\lib\WstClient.js:32:46) WS connect error: Error: connect ETIMEDOUT <wstunnel server IP>:8080

U:\node_modules>node wstunnel/bin/wstt.js -c -t stdio:mxrun.de:8080 -p http://proxy.local:8080 https://<wstunnel server hostname>:8080
[Mar 07 2018 14:38:58.208 GMT+0100](wstunnel\lib\WstClient.js:32:46) WS connect error: Error: getaddrinfo ENOTFOUND <wstunnel server hostname> <wstunnel server hostname>:8080
[Mar 07 2018 14:38:58.226 GMT+0100](wstunnel\lib\WstClient.js:31:43) HTTP connect error: Error: getaddrinfo ENOTFOUND <wstunnel server hostname> <wstunnel server hostname>:8080
{ Error: getaddrinfo ENOTFOUND <wstunnel server hostname> <wstunnel server hostname>:8080
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '<wstunnel server hostname>',
  host: '<wstunnel server hostname>',
  port: '8080' }

**Comment by mhzed** [comment]
"htts://:8080" contains no hostname, thus the error message?
While using proxy, the wstunnel server host is resolved by the proxy server.
The proxy switch works for me.  If the proxy server requires authentication, try "http://user:pass@proxyhost:port/" as proxy server url.  But FYI I've never tested proxy server authentication myself.
