### ISSUE TITLE
Can you tunnel RDP using wstunnel?

### ISSUE THREAD

**Issue by mihaifm** [mhzed/wstunnel#27]
Not a real issue, just wanted to know if it's possible to tunnel RDP using wstunnel.
Would be a great use case.

thanks

**Comment by mihaifm** [comment]
It worked like a charm for me, but I needed to  tweak some Windows registry settings, to relax the security policy. I can add a use case to your readme, I think it would make a good example.

**Comment by mhzed** [comment]
#28 merged.
