### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by mattcurrycom** [mhzed/wstunnel#29]
npm install wstunnel
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
/root
└── wstunnel@1.2.5 

npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by mhzed** [comment]
Run:  npm install -g wstunnel

**Comment by mattcurrycom** [comment]
Works, tyvm.  Might put that in the readme
