### ISSUE TITLE
Why do you open new ws connection for each tcp conn?

### ISSUE THREAD

**Issue by umaxfun** [mhzed/wstunnel#35]
Hi there! Thanks for your awesome work :)

I have a question on the architecture: why do you open a new ws connection for each TCP connection? Why not multiplex all messages in one and only one websocket channel? It'd be better for my case to have one ws connection, through which all the traffic goes. How do you think, would it work over one channel? Can I end up with a working multiplexor OR it'd be better to live with multiple connections?

**Comment by mhzed** [comment]
Thanks.

No particular reason other than this is the easiest approach.  If you setup SSH tunnel or OpenVPN on top of wstunnel then you get multiplexing by default.   The intention of wstunnel was purely to circumvent those pesky strict firewalls, I mostly rely on SSH when I need fancier tunnelling options.
