### ISSUE TITLE
Invalid tunnel option 3333

### ISSUE THREAD

**Issue by SamDecrock** [mhzed/wstunnel#38]
At the server, I'm running

    wstunnel -s 0.0.0.0:8888 -t localhost:2222

At the client, I'm running 

    wstunnel -t 3333 ws://localhost:8888

Yet, I'm getting the error

    Invalid tunnel option 3333

If I specify the host and port from the client, it works:

    wstunnel -t 3333:localhost:2222 ws://localhost:8888

**Comment by mhzed** [comment]
Good catch.  Fixed in 1.3.3.
