### ISSUE TITLE
Error running the tunnel

### ISSUE THREAD

**Issue by Santhoshkumard11** [mhzed/wstunnel#39]
I get this when i run it on port 8080. But when I choose to run on a different port nothing starts. It's just blank. 
Do we have to configure something else to make it run? need some help on this
Thanks in advance

```
root@localhost:~# wstunnel -s 8080
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1307:16)
    at listenInCluster (net.js:1355:12)
    at doListen (net.js:1492:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1334:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
```

**Comment by josedanielr** [comment]
When the service starts successfully it does not print anything until a tunnel is established, so it is normal. Regarding the error, as it says, you should have something that is already using the 8080 port.

**Comment by Santhoshkumard11** [comment]
@josedanielr  Oh! Got it. Thanks for the clarification.
