### ISSUE TITLE
listen EACCES error

### ISSUE THREAD

**Issue by particlememory** [mhzed/wstunnel#4]
Hi mhzed and bylevel, first thank for the great tool.

I found out this is the issue with environment, due to my environment do not able to bind to localhost, see next comment.

I facing some problem when running, can you figure out what I do wrong?
Normally I will run node wstt.js -s 8080, instead of wstunnel as I do not have root access to install in global.

./wstunnel -s 8080                                                     
               
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
 
events.js:48
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EACCES
    at errnoException (net.js:670:11)
    at Array.0 (net.js:756:28)
    at EventEmitter._tickCallback (node.js:190:38)

**Comment by particlememory** [comment]
Sorry, should be my mistake not configure properly. Thanks!

**Comment by particlememory** [comment]
I found this is my environment issue when setup on OpenShift.
I change the following line in wst_server.js
```javascript
this.httpServer.listen(port, process.env.OPENSHIFT_nodejs_IP, function() {
```
However next error happen when I send tcp over tunnel (I am tunneling redis connection)

/var/lib/openshift/554dd0d0fcf9336e9d00005a/app-root/runtime/repo/node_modules/wstunnel/lib/wst_server.js:61
            return this._reject(request, "Tunnel connect error to " + remoteAd
                        ^
TypeError: Object #<Socket> has no method '_reject'
    at Socket.<anonymous> (/var/lib/openshift/554dd0d0fcf9336e9d00005a/app-root/runtime/repo/node_modules/wstunnel/lib/wst_server
.js:61:25)

**Comment by mhzed** [comment]
The root cause was that your TCP connection failed,  and due to bug in the code, the error shown was "no method '_reject'".
