### ISSUE TITLE
Unable to bind server to specific IP

### ISSUE THREAD

**Issue by uidzero** [mhzed/wstunnel#6]
```
$ ./wstt.js -s 2222
Thu Aug 06 2015 14:41:27 GMT+0000 (UTC) Server is listening on port 2222

# lsof -ni|grep node
node      5857   wstunnel   10u  IPv4 25660001      0t0  TCP *:2222 (LISTEN)
```
[...]

```
$ ./wstt.js -s 127.0.0.1:2222 
Thu Aug 06 2015 14:40:43 GMT+0000 (UTC) Server is listening on port 127.0.0.1:2222

# lsof -ni|grep node
#
```
It also creates the -s target as a socket in ```.```:
```
srwxrwxr-x 1 wstunnel wstunnel     0 Aug  6 14:40 127.0.0.1:2222
```

It doesn't seem to create the socket when just the port is specified.

If it's listening to external traffic then most of the purpose of putting it behind an HTTPS proxy is defeated.

**Comment by uidzero** [comment]
I see these lines in ```lib/wst_server.js```:

```
          } else {
            if (!uri.query.dst) {
              return _this._reject(request, "No tunnel target specified");
            }
            remoteAddr = uri.query.dst;
            _ref1 = remoteAddr.split(":"), host = _ref1[0], port = _ref1[1];
          }
```

If this is the correct section then it is failing silently somehow. I don't know nodejs well enough to track down the issue further.

**Comment by mhzed** [comment]
Right you've found an old bug.  
The new version should fix it.
